### PR TITLE
Istio 165 fix

### PR DESCRIPTION
**Pull request by cbron**
Moving 1.6.5 to main folder, deleting 1.6.4

### CODE REVIEW

**Review by brendarearden — APPROVED** [review]
LGTM

**Comment by StrongMonkey** [comment]
@cbron can we also delete 1.6.4?

**Comment by cbron** [comment]
@StrongMonkey fixed

**Comment by StrongMonkey** [comment]
@cbron Also can you rebase on the latest master? It should turn on some validation on CI.

**Review by StrongMonkey — APPROVED** [review]

**Pull request merged**
